# Generated by Django 4.2.1 on 2023-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="currency",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_symbol",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="stock",
            name="timezone",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name="stock",
            table="stock_data",
        ),
    ]
