# Generated by Django 4.2.1 on 2023-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_alter_stock_currency_alter_stock_stock_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="id",
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_symbol",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
